package compiler;

import java.io.IOException;
//ANTLR packages
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import lexparse.*;

/**
 * This class contains the main method which compiles a given .kc file to a .class file
 * and writes it to a specific location
 * 
 * @author Kirin Sharma, Dr. Robert Kelley
 * @version 1.0
 * Assignment 5
 * CS322 - Compiler Construction
 * Spring 2024
 */

 public class kcc
 {
    public static void main(String[] args) 
    {
        // Variables for classes generated by antlr
        CharStream input;
        KnightCodeLexer lexer;
        CommonTokenStream tokens;
        KnightCodeParser parser;

        try
        {
            input = CharStreams.fromFileName(args[0]);  // get the input
            lexer = new KnightCodeLexer(input); // create the lexer
            tokens = new CommonTokenStream(lexer); // create the token stream
            parser = new KnightCodeParser(tokens); // create the parser
            String outputName = args[1]; // the name of the output file read from command line arguments

            ParseTree tree = parser.file();  // set the start location of the parser
            
            // Utilize a CustomVisitor to traverse tree and write corresponding bytecode
            CustomVisitor<Void> visitor = new CustomVisitor<Void>(outputName);
            visitor.visit(tree); // calls method to traverse tree and write bytecode
            visitor.writeFooter(); // call to helper method to wrtite footer of .class file

            // Write bytes created by above CustomVisitor to the specified output file; writeFile credit: Dr. Robert Kelly
            byte[] b = visitor.getByteArray();
            Utilities.writeFile(b, outputName + ".class");
        }
        catch(IOException e)
        {
            System.out.println("Unable to compile. See error message: "); // Should only print in the event of a compilation error
            System.out.println(e.getMessage());
        }

    } // end main

 } // end class
 